apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-static
  labels:
    app.kubernetes.io/name: frontend-static
    app.kubernetes.io/instance: frontend-static
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: dummy
    app.kubernetes.io/part-of: admission-webhook-example
    app.kubernetes.io/managed-by: kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-static
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-static
    spec:
      containers:
      - name: frontend-static
        image: ailtonmsj/frontend-static:v1
        imagePullPolicy: IfNotPresent